### ISSUE TITLE
Decrease the cron frequency

### ISSUE THREAD

**Issue by ev-br** [OpenMathLib/BLAS-Benchmarks#7]
ATM cron runs hourly to assess the CI jitter. Need to flip it to a more civilized pace.

**Comment by martin-frbg** [comment]
Looks to me as if job output got stored every thirty minutes right now, which seems a bit excessive ? Also I'm getting numerous job notifications in my account about  "pages build and deployment workflow run cancelled for gh-pages branch" stating a job got cancelled due to a higher priority waiting request

**Comment by ev-br** [comment]
Indeed, it was hourly. Let me flip it to every 6 hours so that we get some handle on the amount of jitter after the renames (was daxpy, is axpy etc)

**Comment by ev-br** [comment]
Run weekly now.
